version: "3.8"

services:
  postgresdb:
    image: postgres:16.2-bullseye
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres # if not specified, the default database will be 'root'
    ports:
      - "5432:5432"
    volumes:
#      - ./postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

# docker-compose exec -it postgresdb bash -c "psql"