services:
  postgresql:
    image: postgres:15.10
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
#    volumes:
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

# docker-compose up -d --build
# docker exec -it postgresql bash
# psql -U root -d test_db
# pg_dump -U root -d test_db --schema-only > test_db.sql
# docker cp postgresql:/test_db.sql .