version: '3.8'

services:
  mysqldb:
    image: mysql:8.0.36-debian
    container_name: mysqldb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: order
    command:
      ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

# docker-compose up -d --build
# docker-compose exec -it mysqldb bash -c "mysql -proot"
# mysql -proot