version: '3.8'

services:
  mongodb:
    image: mongo:5.0.25
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: mongo_express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      [mongodb]

volumes:
# This section defines a volume named mongo.
# The curly braces {} after the colon indicate
# that this volume configuration is empty.
# ----------------------------------------------------------
# An empty volume configuration in Docker Compose means:
# 1 - An unnamed volume will be created on the host machine.
# 2 - This volume won't have a specific name assigned to it.
  mongo: {}

# docker exec -it mongodb bash -c "mongosh -u root -p root"
