version: '3.8'

services:
  mongodb:
    image: mongo:5.0.25
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: mongo_express
    ports:
      - "9000:8081"
    environment:
      # the username and password for some reason are still 'admin:pass'
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      [mongodb]

volumes:
  mongo: {}

# docker exec -it mongodb bash -c "mongosh -u root -p root"