version: "3.8"

services:
  postgresdb:
    image: postgres:16.2-bullseye
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

# docker-compose exec -it postgresdb bash -c "psql"