version: '3.8'

services:
  db:
    image: mysql:8.0.36-debian
    container_name: mysql1
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_test
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

# docker-compose up -d --build
# docker-compose exec -it db bash -c "mysql -proot"
# mysql -proot