version: "3.8"

services:
  mysqldb:
    image: mysql:8.0.36-debian
    container_name: mysqldb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      #      - ./mysql-data:/var/lib/mysql
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]

  mongodb:
    image: mongo:5.0.25
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    container_name: "keycloak"
    volumes:
      - ./.docker-data/keycloak-data:/opt/keycloak/data
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "4000:8080"
    command:
      [ "start-dev", "--http-port", "8080" ]

volumes:
  mongo: { }

# docker-compose exec -it mysqldb bash -c "mysql -proot"
# docker exec -it mongodb bash -c "mongosh -u root -p root"